# Generated by Django 6.0 on 2025-12-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('resident', 'Житель'), ('uk_user', 'Пользователь УК'), ('dba', 'DBA - менеджер данных'), ('django_admin', 'Администратор Django (ИТ)')], default='resident', max_length=20, verbose_name='Роль'),
        ),
    ]
