# Generated by Django 6.0 on 2025-12-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('uk_user', 'Пользователь УК'), ('dba', 'DBA - менеджер данных'), ('django_admin', 'Администратор Django (ИТ)')], default='uk_user', max_length=20, verbose_name='Роль'),
        ),
    ]
