# Generated by Django 6.0 on 2025-12-14 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(max_length=50, unique=True, verbose_name='ID промпта')),
                ('prompt_type', models.CharField(choices=[('system', 'Системный промпт'), ('greeting', 'Приветствие'), ('address_check', 'Проверка адреса'), ('address_not_found', 'Адрес не найден'), ('farewell', 'Прощание'), ('error', 'Ошибка'), ('profanity_warning', 'Предупреждение о ругательствах'), ('default', 'Ответ по умолчанию')], max_length=20, verbose_name='Тип промпта')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание для чего используется')),
                ('content', models.TextField(verbose_name='Содержание промпта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'AI промпт',
                'verbose_name_plural': 'AI промпты',
                'ordering': ['prompt_type', 'prompt_id'],
            },
        ),
    ]
