# Generated by Django 6.0 on 2025-12-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_aiprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('category', models.CharField(choices=[('plumbing', 'Сантехника'), ('heating', 'Отопление'), ('electrical', 'Электрика'), ('elevator', 'Лифт'), ('building', 'Строительные работы'), ('cleaning', 'Уборка'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('incident_type', models.CharField(choices=[('emergency', 'Аварийная'), ('planned', 'Плановая'), ('consultation', 'Консультация')], max_length=20, verbose_name='Тип инцидента')),
                ('location_type', models.CharField(choices=[('apartment', 'Квартира'), ('building', 'Подъезд/МКД'), ('territory', 'Придомовая территория'), ('common', 'Общее')], max_length=20, verbose_name='Тип локации')),
                ('tags', models.TextField(blank=True, help_text='Теги через запятую', verbose_name='Теги')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова через запятую', verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category', 'name'],
            },
        ),
    ]
