# Generated by Django 6.0 on 2025-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('incident', 'Инцидент/Авария'), ('water', 'Водоснабжение/Канализация'), ('electricity', 'Электричество'), ('heating', 'Отопление'), ('gas', 'Газ'), ('elevator', 'Лифт'), ('door', 'Двери/Замки'), ('window', 'Окна'), ('roof', 'Крыша'), ('other', 'Другое')], db_index=True, max_length=50, verbose_name='Тип паттерна')),
                ('keyword', models.CharField(max_length=100, verbose_name='Ключевое слово')),
                ('weight', models.FloatField(default=1.0, help_text='Вес keyword (0.1 - 10.0). Отрицательный = инверсия.', verbose_name='Вес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Семантический паттерн',
                'verbose_name_plural': 'Семантические паттерны',
                'ordering': ['pattern_type', '-weight', 'keyword'],
                'indexes': [models.Index(fields=['pattern_type'], name='portal_sema_pattern_a1de3e_idx'), models.Index(fields=['keyword'], name='portal_sema_keyword_0e2fb3_idx'), models.Index(fields=['is_active'], name='portal_sema_is_acti_309c8d_idx')],
                'unique_together': {('pattern_type', 'keyword')},
            },
        ),
    ]
