# Generated by Django 6.0 on 2026-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_semanticpattern'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE services_catalog
                ADD COLUMN IF NOT EXISTS tags TEXT DEFAULT '',
                ADD COLUMN IF NOT EXISTS keywords TEXT DEFAULT '';
            """,
            reverse_sql="""
                ALTER TABLE services_catalog
                DROP COLUMN IF EXISTS tags,
                DROP COLUMN IF EXISTS keywords;
            """
        ),
    ]
