# Generated by Django 6.0 on 2026-01-14 07:48
# Модифицировано: ServicesCatalog - unmanaged модель, не создаем через миграцию

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20260114_0953'),
    ]

    operations = [
        # Удаляем устаревшую модель Service (portal_service)
        # Данные перенесены в services_catalog (tags/keywords)
        # Архивный код: old/portal_models_Service_backup.py
        migrations.DeleteModel(
            name='Service',
        ),
    ]
