# Generated by Django 6.0 on 2026-01-14
# Удаление поля keywords (дублирует tags, не используется в нормализованной БД)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_service_model'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE services_catalog
                DROP COLUMN IF EXISTS keywords;
            """,
            reverse_sql="""
                ALTER TABLE services_catalog
                ADD COLUMN IF NOT EXISTS keywords TEXT DEFAULT '';
            """
        ),
    ]
