# Generated by Django 6.0 on 2026-02-09
# Ручная корректировка: убраны CreateModel для существующих таблиц (Ольга:Рефакторинг 09.02.2026)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_add_user_timezone'),
    ]

    operations = [
        # Изменение verbose_name для AIPrompt (префикс "AI и Промпты:")
        migrations.AlterModelOptions(
            name='aiprompt',
            options={'ordering': ['prompt_type', 'prompt_id'], 'verbose_name': 'AI и Промпты: Промпт', 'verbose_name_plural': 'AI и Промпты: Промпты'},
        ),
        # Добавление поля is_test для защиты боевых промптов
        migrations.AddField(
            model_name='aiprompt',
            name='is_test',
            field=models.BooleanField(default=False, help_text='True = тестовый (для экспериментов), False = боевой (используется в продакшне)', verbose_name='Тестовый'),
        ),
    ]
    # Примечание: CreateModel для PromptTemplate, PromptPreset, LLMTestResult убраны
    # Эти модели уже существуют в БД, мы только изменили их app_label (Ольга:Рефакторинг 09.02.2026)
