# Generated by Django 6.0 on 2026-02-19
# Добавление полей для исполнителей и сотрудников УК

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_add_is_test_to_aiprompt'),
    ]

    operations = [
        # Добавление поля specialization для исполнителей
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(
                blank=True,
                choices=[(None, 'Не указана'), ('plumber', 'Сантехник'), ('electrician', 'Электрик'), ('general_worker', 'Разнорабочий')],
                max_length=20,
                null=True,
                verbose_name='Специализация исполнителя'
            ),
        ),
        # Добавление поля job_title для должностей сотрудников УК
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(
                blank=True,
                choices=[(None, 'Не указана'), ('manager', 'Менеджер УК'), ('dispatcher', 'Диспетчер'), ('chief_engineer', 'Главный инженер')],
                max_length=20,
                null=True,
                verbose_name='Должность'
            ),
        ),
        # Добавление поля responsibilities для обязанностей
        migrations.AddField(
            model_name='userprofile',
            name='responsibilities',
            field=models.TextField(
                blank=True,
                help_text='Описание обязанностей сотрудника',
                null=True,
                verbose_name='Обязанности'
            ),
        ),
        # Обновление роли - добавление executor
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[('uk_user', 'Пользователь УК'), ('executor', 'Исполнитель'), ('dba', 'DBA - менеджер данных'), ('django_admin', 'Администратор Django (ИТ)')],
                default='uk_user',
                max_length=20,
                verbose_name='Роль'
            ),
        ),
    ]
