# Generated by Django 6.0 on 2026-02-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_add_executor_fields'),
    ]

    operations = [
    ]
