# Generated by Django 6.0 on 2026-03-18 10:20

from django.db import migrations, models


def rename_dba_to_director_uk(apps, schema_editor):
    """Обновление данных: переименование роли 'dba' в 'direktor_uk'"""
    UserProfile = apps.get_model('portal', 'UserProfile')
    UserProfile.objects.filter(role='dba').update(role='direktor_uk')


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_add_is_at_scene'),
    ]

    operations = [
        # Сначала обновляем данные
        migrations.RunPython(rename_dba_to_director_uk, migrations.RunPython.noop),

        # Затем изменяем choices поля role
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('uk_user', 'Пользователь УК'),
                    ('direktor_uk', 'Директор УК'),
                    ('django_admin', 'Администратор Django (ИТ)'),
                    ('executor', 'Исполнитель'),
                    ('resident', 'Житель'),
                ],
                default='resident',
                max_length=20,
                verbose_name='Роль'
            ),
        ),
    ]
