# Generated by Django 6.0 on 2026-03-26 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_rename_dba_to_director_uk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCatalog',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID услуги')),
                ('scenario_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('type_name', models.CharField(help_text="ВРЕМЕННО: Устаревшее текстовое поле. Используйте FK поле 'type'.", max_length=100, verbose_name="Тип услуги (устарело, использовать 'type')")),
                ('localization_name', models.CharField(help_text="ВРЕМЕННО: Устаревшее текстовое поле. Используйте FK поле 'localization'.", max_length=100, verbose_name="Локализация (устарело, использовать 'localization')")),
                ('category_name', models.CharField(help_text="ВРЕМЕННО: Устаревшее текстовое поле. Используйте FK поле 'category'.", max_length=255, verbose_name="Категория (устарело, использовать 'category')")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('route_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Маршрут')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Служебная услуга')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Справочник услуг',
                'db_table': 'services_catalog',
                'ordering': ['category', 'scenario_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromptPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название варианта теста', max_length=200, verbose_name='Название пресета')),
                ('variable_values', models.JSONField(help_text='JSON с подстановками для переменных шаблона', verbose_name='Значения переменных')),
                ('custom_prompt', models.TextField(blank=True, help_text='Если заполнено - заменяет шаблон', verbose_name='Измененный текст промпта')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли этот пресет для тестирования', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'AI и Промпты: Тестовый пресет',
                'verbose_name_plural': 'AI и Промпты: Тестовые пресеты',
                'db_table': 'llm_tester_promptpreset',
                'ordering': ['prompt', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('Europe/Moscow', 'Москва (UTC+3)'), ('Europe/Kaliningrad', 'Калининград (UTC+2)'), ('Europe/Samara', 'Самара (UTC+4)'), ('Asia/Yekaterinburg', 'Екатеринбург (UTC+5)'), ('Asia/Omsk', 'Омск (UTC+6)'), ('Asia/Krasnoyarsk', 'Красноярск (UTC+7)'), ('Asia/Irkutsk', 'Иркутск (UTC+8)'), ('Asia/Yakutsk', 'Якутск (UTC+9)'), ('Asia/Vladivostok', 'Владивосток (UTC+10)'), ('Asia/Magadan', 'Магадан (UTC+11)'), ('Asia/Kamchatka', 'Камчатка (UTC+12)')], default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс'),
        ),
        migrations.CreateModel(
            name='LLMTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yandexgpt', 'YandexGPT'), ('gigachat', 'GigaChat')], help_text='LLM провайдер (YandexGPT, GigaChat)', max_length=20, verbose_name='Провайдер')),
                ('model', models.CharField(help_text='Название модели (например: YandexGPT Pro, GigaChat-2)', max_length=50, verbose_name='Модель')),
                ('prompt_text', models.TextField(help_text='Полный текст промпта который был отправлен', verbose_name='Отправленный промпт')),
                ('response_text', models.TextField(help_text='Ответ который вернула модель', verbose_name='Ответ LLM')),
                ('usage_info', models.JSONField(help_text='Токены, стоимость, время обработки (JSON)', verbose_name='Метрики')),
                ('status', models.CharField(choices=[('success', 'Успех'), ('error', 'Ошибка')], default='success', help_text='Успешно ли выполнен запрос', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, help_text='Текст ошибки если статус = error', verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(help_text='Кто запустил тест', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('preset', models.ForeignKey(blank=True, help_text='Какой пресет был протестирован', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='portal.promptpreset', verbose_name='Использованный пресет')),
            ],
            options={
                'verbose_name': 'AI и Промпты: Результат теста LLM',
                'verbose_name_plural': 'AI и Промпты: Результаты тестов LLM',
                'db_table': 'llm_tester_llmtestresult',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название микросервиса или промпта', max_length=200, verbose_name='Название промпта')),
                ('slug', models.SlugField(help_text='Идентификатор промпта (может быть несколько версий с одинаковым slug)', max_length=100, verbose_name='Slug')),
                ('prompt_type', models.CharField(choices=[('filter_detection', 'FilterDetectionService'), ('main_agent', 'MainAgent'), ('problem_accumulation', 'ProblemAccumulationService'), ('custom', 'Кастомный')], help_text='Какой микросервис использует этот промпт', max_length=50, verbose_name='Тип промпта')),
                ('microservice', models.CharField(blank=True, help_text='Имя микросервиса для связки с логами (FilterDetectionService, MainAgent, ProblemAccumulationService и т.д.)', max_length=100, verbose_name='Микросервис')),
                ('template', models.TextField(help_text='Текст промпта с переменными в формате {variable_name}', verbose_name='Шаблон промпта')),
                ('description', models.TextField(blank=True, help_text='Для чего используется этот шаблон', verbose_name='Описание')),
                ('version_number', models.IntegerField(default=1, help_text='Порядковый номер версии (1, 2, 3, ...)', verbose_name='Номер версии')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли этот шаблон для тестирования', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('parent_version', models.ForeignKey(blank=True, help_text='Предыдущая версия этого промпта (для версионирования)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='portal.prompttemplate', verbose_name='Предыдущая версия')),
            ],
            options={
                'verbose_name': 'AI и Промпты: Шаблон промпта',
                'verbose_name_plural': 'AI и Промпты: Шаблоны промптов',
                'db_table': 'llm_tester_prompttemplate',
                'ordering': ['prompt_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='promptpreset',
            name='prompt',
            field=models.ForeignKey(help_text='Базовый шаблон для этого пресета', on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='portal.prompttemplate', verbose_name='Шаблон промпта'),
        ),
    ]
