# Generated by Django 6.0 on 2026-03-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_servicescatalog_promptpreset_userprofile_timezone_and_more'),
    ]

    operations = [
        # РЕГИСТРАЦИЯ МОДЕЛИ ServicesCatalog БЕЗ ИЗМЕНЕНИЙ БД
        #
        # ВОССТАНОВЛЕНО (2026-03-26): FK-структура services_catalog
        #
        # ТАБЛИЦА УЖЕ СУЩЕСТВУЕТ В БД:
        #   - services_catalog (создана вручную)
        #   - с полями: type_id, category_id, localization_id (FK)
        #   - с полями: type_name, category_name, localization_name (текстовые)
        #
        # ИСПОЛЬЗУЕМ SeparateDatabaseAndState:
        #   - state_operations: регистрируем модель в Django (CreateModel)
        #   - database_operations: НИЧЕГО (пустой список) - НЕ изменяем таблицу
        #
        # РЕЗУЛЬТАТ:
        #   - Django "увидит" модель ServicesCatalog
        #   - Django увидит FK поля (type, category, localization)
        #   - БД НЕ будет изменена
        #   - Ошибок CREATE TABLE/ALTER TABLE не будет
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ServicesCatalog',
                    fields=[
                        ('service_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID услуги')),
                        ('scenario_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                        # FK поля (ВОССТАНОВЛЕНЫ - 2026-03-26)
                        ('type', models.ForeignKey(
                            'nsi.RefServiceType',
                            db_column='type_id',
                            on_delete=models.PROTECT,
                            verbose_name='Тип услуги',
                            related_name='+',
                            help_text='Инцидент или Запрос'
                        )),
                        ('category', models.ForeignKey(
                            'nsi.RefCategory',
                            db_column='category_id',
                            on_delete=models.PROTECT,
                            verbose_name='Категория',
                            related_name='+',
                            help_text='Категория услуги (11 категорий)'
                        )),
                        ('localization', models.ForeignKey(
                            'nsi.RefLocalization',
                            db_column='localization_id',
                            on_delete=models.PROTECT,
                            verbose_name='Локализация',
                            related_name='+',
                            help_text='Общедомовое или Индивидуальное'
                        )),
                        # УСТАРЕВШИЕ ТЕКСТОВЫЕ ПОЛЯ (ВРЕМЕННО ОСТАВЛЕНЫ)
                        ('type_name', models.CharField(
                            max_length=100,
                            verbose_name="Тип услуги (устарело, использовать 'type')",
                            help_text="ВРЕМЕННО: Устаревшее текстовое поле. Используйте FK поле 'type'."
                        )),
                        ('localization_name', models.CharField(
                            max_length=100,
                            verbose_name="Локализация (устарело, использовать 'localization')",
                            help_text="ВРЕМЕННО: Устаревшее текстовое поле. Используйте FK поле 'localization'."
                        )),
                        ('category_name', models.CharField(
                            max_length=255,
                            verbose_name="Категория (устарело, использовать 'category')",
                            help_text="ВРЕМЕННО: Устаревшее текстовое поле. Используйте FK поле 'category'."
                        )),
                        # Остальные поля (без изменений)
                        ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                        ('route_name', models.CharField(max_length=150, blank=True, null=True, verbose_name='Маршрут')),
                        ('is_internal', models.BooleanField(default=False, verbose_name='Служебная услуга')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                    ],
                    options={
                        'managed': False,
                        'db_table': 'services_catalog',
                        'verbose_name': 'Услуга',
                        'verbose_name_plural': 'Справочник услуг',
                        'ordering': ['category', 'scenario_name'],
                    },
                ),
            ],
            database_operations=[
                # ПУСТОЙ СПИСОК - НЕ изменяем таблицу, она УЖЕ существует
            ],
        ),
    ]
