# Generated by Django 6.0 on 2026-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_register_servicescatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('service_object_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('building_id', models.IntegerField(verbose_name='ID здания')),
                ('unit_id', models.IntegerField(blank=True, null=True, verbose_name='ID помещения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Объект обслуживания',
                'verbose_name_plural': 'Объекты обслуживания',
                'db_table': 'service_objects',
                'ordering': ['service_object_id'],
                'managed': False,
            },
        ),
    ]
