# Generated by Claude

from django.db import migrations

def sync_role_from_membership_to_job_title(apps, schema_editor):
    """
    Синхронизирует роль из UserCompanyMembership в UserProfile.job_title

    ЛОГИКА:
    1. Для каждого пользователя с UserProfile
    2. Найти primary membership (is_primary=True или последний активный)
    3. Сопоставить role_code → job_title:
       - 'direktor_uk' → 'director'
       - 'chief_engineer' → 'chief_engineer'
       - 'executor' → None (нет должности в списке)
       - 'uk_user' → 'manager'
       - 'resident' → None
       - 'contractor' → None
       - 'django_admin' → None
    4. Обновить UserProfile.job_title

    КОНФЛИКТЫ:
    - Если у пользователя несколько membership → берем primary
    - Если job_title уже заполнен → НЕ перезаписываем (приоритет ручному вводу)
    - Если role_code нет в маппинге → пропускаем
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('portal', 'UserProfile')
    UserCompanyMembership = apps.get_model('work_orders', 'UserCompanyMembership')

    # Маппинг role_code → job_title
    role_to_job_title = {
        'direktor_uk': 'director',
        'chief_engineer': 'chief_engineer',
        'uk_user': 'manager',
        'manager': 'manager',  # Для обратной совместимости
        'dispatcher': 'dispatcher',
        # executor, resident, contractor, django_admin → None (нет в списке)
    }

    # Статистика
    updated_count = 0
    skipped_no_membership = 0
    skipped_already_set = 0
    skipped_no_mapping = 0
    conflicts = []

    for profile in UserProfile.objects.select_related('user').all():
        user = profile.user

        # Пропускаем если job_title уже задан вручную
        if profile.job_title is not None and profile.job_title != '':
            skipped_already_set += 1
            continue

        # Ищем primary membership
        membership = UserCompanyMembership.objects.filter(
            user=user,
            is_active=True,
            date_to__isnull=True
        ).filter(
            # Сначала primary
            is_primary=True
        ).first()

        # Если нет primary - берем любой активный
        if not membership:
            membership = UserCompanyMembership.objects.filter(
                user=user,
                is_active=True,
                date_to__isnull=True
            ).first()

        if not membership:
            skipped_no_membership += 1
            continue

        # Сопоставляем role_code → job_title
        role_code = membership.role_code
        job_title = role_to_job_title.get(role_code)

        if job_title is None:
            skipped_no_mapping += 1
            if role_code not in ['executor', 'resident', 'contractor', 'django_admin']:
                conflicts.append({
                    'user_id': user.id,
                    'username': user.username,
                    'role_code': role_code,
                    'reason': 'Нет маппинга role_code → job_title'
                })
            continue

        # Обновляем job_title
        profile.job_title = job_title
        profile.save(update_fields=['job_title'])
        updated_count += 1

    # Выводим статистику в миграцию (для логов)
    print(f"\n=== Синхронизация role → job_title ===")
    print(f"Обновлено: {updated_count}")
    print(f"Пропущено (нет membership): {skipped_no_membership}")
    print(f"Пропущено (уже задан): {skipped_already_set}")
    print(f"Пропущено (нет маппинга): {skipped_no_mapping}")
    if conflicts:
        print(f"\nКонфликты ({len(conflicts)}):")
        for c in conflicts[:10]:  # Первые 10
            print(f"  - {c['username']}: {c['role_code']} ({c['reason']})")
        if len(conflicts) > 10:
            print(f"  ... и еще {len(conflicts) - 10}")
    print(f"====================================\n")


class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0019_migrate_primary_company_and_department'),
        ('work_orders', '0013_cleanup_sla_and_add_company_sequence_numbers'),
    ]

    operations = [
        migrations.RunPython(sync_role_from_membership_to_job_title),
    ]
