# Generated by Django 6.0 on 2026-01-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicativeScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=100, unique=True, verbose_name='Название скрипта')),
                ('script_type', models.CharField(choices=[('fallback', 'Fallback при ошибке AI'), ('pause', 'Заполнение паузы (audio)'), ('greeting', 'Приветствие'), ('clarification', 'Уточняющий вопрос'), ('confirmation', 'Подтверждение'), ('error', 'Сообщение об ошибке')], db_index=True, max_length=50, verbose_name='Тип скрипта')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('audio', 'Аудио (телефон)'), ('both', 'Оба канала')], db_index=True, max_length=50, verbose_name='Канал связи')),
                ('text', models.TextField(verbose_name='Текст скрипта')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON условия для triggerа', verbose_name='Условия использования')),
                ('priority', models.FloatField(default=1.0, verbose_name='Приоритет')),
                ('max_uses_per_day', models.IntegerField(default=-1, help_text='-1 = без ограничений', verbose_name='Макс. использований/день')),
                ('min_dialog_turn', models.IntegerField(default=0, verbose_name='Мин. номер хода')),
                ('max_dialog_turn', models.IntegerField(default=-1, help_text='-1 = без ограничений', verbose_name='Макс. номер хода')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Коммуникативный скрипт',
                'verbose_name_plural': 'Коммуникативные скрипты',
                'ordering': ['script_type', '-priority', 'script_name'],
                'indexes': [models.Index(fields=['script_type'], name='message_han_script__1faa3b_idx'), models.Index(fields=['channel'], name='message_han_channel_639251_idx'), models.Index(fields=['is_active'], name='message_han_is_acti_05d005_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_id', models.UUIDField(verbose_name='ID диалога')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('maxchat', 'Мессенджер Макс'), ('web', 'Веб-сайт'), ('test_bot', 'Тестовый бот-имитатор'), ('transcriber', 'Голосовой транскрибатор')], db_index=True, max_length=50, verbose_name='Канал связи')),
                ('direction', models.CharField(choices=[('inbound', 'Входящее (от пользователя)'), ('outbound', 'Исходящее (от бота)'), ('system', 'Системное')], db_index=True, max_length=20, verbose_name='Направление')),
                ('message_id', models.CharField(db_index=True, max_length=255, verbose_name='ID сообщения в канале')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='ID сессии диалога')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ID пользователя в канале')),
                ('django_user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID пользователя Django')),
                ('message_type', models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее'), ('system', 'Системное')], db_index=True, max_length=20, verbose_name='Тип сообщения')),
                ('message_content', models.TextField(verbose_name='Текст сообщения')),
                ('processing_stage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стадия обработки')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Уверенность определения')),
                ('service_detected_id', models.IntegerField(blank=True, null=True, verbose_name='ID определенной услуги')),
                ('address_extracted', models.JSONField(blank=True, null=True, verbose_name='Извлеченный адрес')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Время обработки (мс)')),
                ('llm_provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='LLM провайдер')),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='LLM модель')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='Количество токенов')),
                ('cost_rub', models.FloatField(blank=True, null=True, verbose_name='Стоимость (руб)')),
                ('metadata', models.JSONField(blank=True, help_text='Дополнительная информация (service_detection, txtPrb, filters и т.д.)', null=True, verbose_name='Метаданные')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время получения')),
            ],
            options={
                'verbose_name': 'Лог сообщения',
                'verbose_name_plural': 'Логи сообщений',
                'db_table': 'dialog_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['channel', 'timestamp'], name='dialog_logs_channel_df2c4e_idx'), models.Index(fields=['session_id', 'timestamp'], name='dialog_logs_session_717966_idx'), models.Index(fields=['user_id', 'channel'], name='dialog_logs_user_id_b539af_idx'), models.Index(fields=['dialog_id'], name='dialog_logs_dialog__28aa49_idx'), models.Index(fields=['message_type'], name='dialog_logs_message_71aa9b_idx')],
            },
        ),
    ]
