# Generated by Django 6.0 on 2025-12-24 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('maxchat', 'Мессенджер Макс'), ('web', 'Веб-сайт'), ('test_bot', 'Тестовый бот-имитатор'), ('transcriber', 'Голосовой транскрибатор')], db_index=True, max_length=20, verbose_name='Канал связи')),
                ('direction', models.CharField(choices=[('inbound', 'Входящее (от пользователя)'), ('outbound', 'Исходящее (от бота)')], db_index=True, max_length=10, verbose_name='Направление')),
                ('message_id', models.CharField(db_index=True, max_length=255, verbose_name='ID сообщения в канале')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='ID пользователя в канале')),
                ('session_id', models.CharField(db_index=True, help_text='Уникальный идентификатор диалога', max_length=255, verbose_name='ID сессии диалога')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация от канала связи', verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время получения')),
                ('django_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Лог сообщения',
                'verbose_name_plural': 'Логи сообщений',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='message_han_channel_2e2da1_idx'), models.Index(fields=['session_id', 'created_at'], name='message_han_session_f7adea_idx'), models.Index(fields=['user_id', 'channel'], name='message_han_user_id_64d5e8_idx')],
            },
        ),
    ]
