# Generated by Django 6.0 on 2025-12-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicativeScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=100, unique=True, verbose_name='Название скрипта')),
                ('script_type', models.CharField(choices=[('fallback', 'Fallback при ошибке AI'), ('pause', 'Заполнение паузы (audio)'), ('greeting', 'Приветствие'), ('clarification', 'Уточняющий вопрос'), ('confirmation', 'Подтверждение'), ('error', 'Сообщение об ошибке')], db_index=True, max_length=50, verbose_name='Тип скрипта')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('audio', 'Аудио (телефон)'), ('both', 'Оба канала')], db_index=True, max_length=50, verbose_name='Канал связи')),
                ('text', models.TextField(verbose_name='Текст скрипта')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON условия для triggerа', verbose_name='Условия использования')),
                ('priority', models.FloatField(default=1.0, verbose_name='Приоритет')),
                ('max_uses_per_day', models.IntegerField(default=-1, help_text='-1 = без ограничений', verbose_name='Макс. использований/день')),
                ('min_dialog_turn', models.IntegerField(default=0, verbose_name='Мин. номер хода')),
                ('max_dialog_turn', models.IntegerField(default=-1, help_text='-1 = без ограничений', verbose_name='Макс. номер хода')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Коммуникативный скрипт',
                'verbose_name_plural': 'Коммуникативные скрипты',
                'ordering': ['script_type', '-priority', 'script_name'],
                'indexes': [models.Index(fields=['script_type'], name='message_han_script__1faa3b_idx'), models.Index(fields=['channel'], name='message_han_channel_639251_idx'), models.Index(fields=['is_active'], name='message_han_is_acti_05d005_idx')],
            },
        ),
    ]
