# Generated by Django 6.0 on 2026-03-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('maxchat', 'Мессенджер Макс'), ('web', 'Веб-сайт'), ('test_bot', 'Тестовый бот-имитатор'), ('transcriber', 'Голосовой транскрибатор'), ('api', 'Внешнее API')], db_index=True, max_length=50, verbose_name='Канал связи'),
        ),
        migrations.CreateModel(
            name='APIErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('auth', 'Ошибка аутентификации'), ('validation', 'Ошибка валидации'), ('processing', 'Ошибка обработки'), ('timeout', 'Таймаут'), ('internal', 'Внутренняя ошибка')], db_index=True, max_length=50, verbose_name='Тип ошибки')),
                ('status_code', models.IntegerField(db_index=True, verbose_name='HTTP статус')),
                ('error_message', models.CharField(db_index=True, max_length=500, verbose_name='Ошибка')),
                ('error_details', models.TextField(blank=True, null=True, verbose_name='Детали ошибки')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Session ID')),
                ('request_id', models.CharField(max_length=100, unique=True, verbose_name='Request ID')),
                ('client_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP клиента')),
                ('client_system', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Клиентская система')),
                ('token_preview', models.CharField(blank=True, max_length=20, verbose_name='Токен (первые символы)')),
                ('request_data', models.JSONField(blank=True, help_text='JSON тело запроса', null=True, verbose_name='Данные запроса')),
                ('message_preview', models.CharField(blank=True, max_length=200, verbose_name='Сообщение (первые символы)')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='User ID')),
                ('nomer', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='NOMER (абонент)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время ошибки')),
            ],
            options={
                'verbose_name': 'Лог ошибок API',
                'verbose_name_plural': 'Логи ошибок API',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'status_code'], name='message_han_timesta_436fc5_idx'), models.Index(fields=['client_ip', 'timestamp'], name='message_han_client__2e9f4e_idx'), models.Index(fields=['session_id', 'timestamp'], name='message_han_session_63255f_idx'), models.Index(fields=['client_system', 'timestamp'], name='message_han_client__c491e1_idx'), models.Index(fields=['error_type', 'timestamp'], name='message_han_error_t_042e33_idx'), models.Index(fields=['nomer'], name='message_han_nomer_181686_idx')],
            },
        ),
    ]
