# Generated by Django 6.0 on 2026-03-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Создание schema request_mgmt
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS request_mgmt;",
            reverse_sql="DROP SCHEMA IF EXISTS request_mgmt CASCADE;",
        ),
        # Создание extension btree_gist для exclusion constraints
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist SCHEMA public;",
            reverse_sql="DROP EXTENSION IF EXISTS btree_gist;",
        ),
    ]
