# Generated by Django 6.0 on 2026-03-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_initial_tables'),
    ]

    operations = [
        # Exclusion constraint для предотвращения пересечения периодов обслуживания
        # одного объекта разными компаниями
        migrations.RunSQL(
            sql="""
                ALTER TABLE request_mgmt.company_object_service_period
                ADD CONSTRAINT ex_comp_obj_period_no_overlap
                EXCLUDE USING gist (
                    object_id WITH =,
                    daterange(date_from, COALESCE(date_to, 'infinity'::date), '[]') WITH &&
                );
            """,
            reverse_sql="""
                ALTER TABLE request_mgmt.company_object_service_period
                DROP CONSTRAINT IF EXISTS ex_comp_obj_period_no_overlap;
            """,
        ),
    ]
