# Generated by Django 6.0 on 2026-03-27

from django.db import migrations


def create_statuses(apps, schema_editor):
    """Создает стартовые статусы заявок"""
    schema_editor.execute("""
        -- Внутренние статусы
        INSERT INTO request_mgmt.work_order_status_ref
        (short_code_en, short_name_ru, status_scope, description_and_transition_rules, sort_order, is_terminal, is_active, created_at, updated_at, is_test)
        VALUES
        ('new_registered', 'Новая', 'internal', 'Заявка только что создана, еще не распределена', 100, false, true, now(), now(), false),
        ('accepted_by_executor', 'Принята исполнителем', 'internal', 'Исполнитель взял заявку в работу', 200, false, true, now(), now(), false),
        ('in_progress', 'В работе', 'internal', 'Ведутся работы по заявке', 300, false, true, now(), now(), false),
        ('on_hold', 'Приостановлена', 'internal', 'Работа по заявке временно приостановлена', 400, false, true, now(), now(), false),
        ('completed', 'Выполнена', 'internal', 'Работы по заявке завершены', 500, true, true, now(), now(), false),
        ('closed', 'Закрыта', 'internal', 'Заявка окончательно закрыта', 600, true, true, now(), now(), false),
        ('cancelled', 'Отменена', 'internal', 'Заявка отменена', 700, true, true, now(), now(), false),
        ('reopened', 'Переоткрыта', 'internal', 'Заявка была переоткрыта после закрытия', 800, false, true, now(), now(), false),

        -- Внешние статусы
        ('accepted', 'Принята', 'external', 'Заявка принята в работу', 100, false, true, now(), now(), false),
        ('in_work', 'В работе', 'external', 'Ведутся работы по заявке', 200, false, true, now(), now(), false),
        ('waiting_for_resident', 'Ожидает жителя', 'external', 'Ожидается действие или информация от жителя', 300, false, true, now(), now(), false),
        ('completed_external', 'Выполнена', 'external', 'Работы по заявке завершены', 400, true, true, now(), now(), false),
        ('closed_external', 'Закрыта', 'external', 'Заявка окончательно закрыта', 500, true, true, now(), now(), false),
        ('cancelled_external', 'Отменена', 'external', 'Заявка отменена', 600, true, true, now(), now(), false),
        ('reopened_external', 'Переоткрыта', 'external', 'Заявка была переоткрыта после закрытия', 700, false, true, now(), now(), false);
    """)


def create_transitions(apps, schema_editor):
    """Создает стартовые переходы статусов"""
    schema_editor.execute("""
        INSERT INTO request_mgmt.work_order_status_transition
        (from_status_id, to_status_id, allowed_role_code, is_system_transition, require_comment,
         require_reason_code, require_resolution_text, require_result_photo, require_executor_assigned,
         is_active, created_at, updated_at, is_test)
        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            NULL as allowed_role_code,
            false as is_system_transition,
            false as require_comment,
            false as require_reason_code,
            false as require_resolution_text,
            false as require_result_photo,
            false as require_executor_assigned,
            true as is_active,
            now() as created_at,
            now() as updated_at,
            false as is_test
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'new_registered') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'accepted_by_executor') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'accepted_by_executor') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'in_progress') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'accepted_by_executor') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'on_hold') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'accepted_by_executor') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'completed') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            NULL,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'in_progress') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'on_hold') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'in_progress') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'completed') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'on_hold') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'in_progress') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'on_hold') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'completed') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'chief_engineer' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'completed') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'closed') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            NULL,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'completed') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'reopened') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'chief_engineer' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'closed') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'reopened') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'direktor_uk' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'new_registered') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'cancelled') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'direktor_uk' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'accepted_by_executor') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'cancelled') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'reopened') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'accepted_by_executor') ts

        UNION ALL

        SELECT
            fs.id as from_status_id,
            ts.id as to_status_id,
            'executor' as allowed_role_code,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            now(),
            now(),
            false
        FROM (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'reopened') fs
        CROSS JOIN (SELECT id FROM request_mgmt.work_order_status_ref WHERE short_code_en = 'in_progress') ts;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_add_exclusion_constraint'),
    ]

    operations = [
        migrations.RunPython(create_statuses, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_transitions, reverse_code=migrations.RunPython.noop),
    ]
