# Generated by Django 6.0 on 2026-03-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0010_remove_lifecycle_fields_and_add_status_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Используем SeparateDatabaseAndState - добавляем модель только в Django состояние, НЕ в БД
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='WorkOrderStatusHistory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-Время')),
                        ('is_test', models.BooleanField(default=False, verbose_name='Тестовый')),
                        ('changed_by', models.ForeignKey(blank=True, db_column='changed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                        ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='work_orders.workorderstatusref', verbose_name='Статус')),
                        ('work_order', models.ForeignKey(db_column='work_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='work_orders.workorder', verbose_name='Заявка')),
                    ],
                    options={
                        'verbose_name': 'История изменения статуса',
                        'verbose_name_plural': 'Истории изменения статусов',
                        'db_table': 'work_order_status_history',
                        'ordering': ['-changed_at'],
                        'indexes': [
                            models.Index(fields=['work_order', '-changed_at'], name='idx_status_hist_work_time'),
                            models.Index(fields=['status'], name='idx_status_hist_status'),
                            models.Index(fields=['changed_by'], name='idx_status_hist_user'),
                        ],
                    },
                ),
            ],
            database_operations=[
                # Пусто - таблица уже создана в предыдущей миграции
            ],
        ),
    ]


