# Generated by Django 6.0 on 2026-04-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0014_remove_sla_policy_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slapolicy',
            options={'ordering': ['company', 'service', 'priority_code'], 'verbose_name': 'SLA-политика', 'verbose_name_plural': 'SLA-политики'},
        ),
        migrations.RemoveConstraint(
            model_name='workorder',
            name='ck_work_order_close_requires_complete_or_cancel',
        ),
        migrations.RemoveConstraint(
            model_name='workorder',
            name='ck_work_order_complete_requires_resolution',
        ),
        migrations.RemoveConstraint(
            model_name='workorderstatusref',
            name='ck_work_order_status_ref_scope',
        ),
        migrations.RemoveIndex(
            model_name='workorderstatusref',
            name='idx_work_status_ref_scope',
        ),
        migrations.AddField(
            model_name='workorderstatusref',
            name='display_name_for_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Для пользователя'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='current_internal_status',
            field=models.ForeignKey(db_column='current_internal_status_id', on_delete=django.db.models.deletion.PROTECT, related_name='status_work_orders', to='work_orders.workorderstatusref', verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='workorderstatusref',
            name='is_terminal',
            field=models.BooleanField(default=False, verbose_name='Конечный статус'),
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='cancelled_by_user',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='closed_by_user',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='completed_by_user',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='current_external_status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='in_progress_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='localized_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='reopened_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='resident_contacted_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workorderstatusref',
            name='status_scope',
        ),
    ]
