# Generated by Django 6.0 on 2025-12-14 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KladrObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код типа')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Регион'), (2, 'Район'), (3, 'Город'), (4, 'Населенный пункт'), (5, 'Улица'), (6, 'Здание'), (7, 'Помещение')], verbose_name='Уровень')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Короткое название')),
            ],
            options={
                'verbose_name': 'Тип объекта КЛАДР',
                'verbose_name_plural': 'Типы объектов КЛАДР',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('import', 'Импорт'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=20, verbose_name='Тип операции')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('records_processed', models.PositiveIntegerField(verbose_name='Обработано записей')),
                ('records_successful', models.PositiveIntegerField(verbose_name='Успешно')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_details', models.TextField(blank=True, verbose_name='Детали ошибок')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
            ],
            options={
                'verbose_name': 'Лог импорта данных',
                'verbose_name_plural': 'Логи импорта данных',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KladrAddressObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код КЛАДР')),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Почтовый индекс')),
                ('okato', models.CharField(blank=True, max_length=11, null=True, verbose_name='ОКАТО')),
                ('oktmo', models.CharField(blank=True, max_length=11, null=True, verbose_name='ОКТМО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kladr.kladraddressobject', verbose_name='Родительский объект')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kladr.kladrobjecttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Адресный объект КЛАДР',
                'verbose_name_plural': 'Адресные объекты КЛАДР',
                'ordering': ['type__level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('building_type', models.CharField(blank=True, max_length=50, verbose_name='Тип дома')),
                ('porch_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество подъездов')),
                ('floor_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='Есть лифт')),
                ('square_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая площадь (м²)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('address_object', models.ForeignKey(limit_choices_to={'type__level__lte': 5}, on_delete=django.db.models.deletion.CASCADE, to='kladr.kladraddressobject', verbose_name='Адресный объект (улица)')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'ordering': ['address_object__name', 'house_number'],
                'unique_together': {('address_object', 'house_number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зоны')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('buildings', models.ManyToManyField(to='kladr.building', verbose_name='Здания в зоне')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Зона обслуживания',
                'verbose_name_plural': 'Зоны обслуживания',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='kladraddressobject',
            index=models.Index(fields=['code'], name='kladr_kladr_code_f19964_idx'),
        ),
        migrations.AddIndex(
            model_name='kladraddressobject',
            index=models.Index(fields=['type', 'name'], name='kladr_kladr_type_id_5a3f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='kladraddressobject',
            index=models.Index(fields=['parent'], name='kladr_kladr_parent__751e18_idx'),
        ),
        migrations.AddIndex(
            model_name='kladraddressobject',
            index=models.Index(fields=['zip_code'], name='kladr_kladr_zip_cod_acd45f_idx'),
        ),
    ]
