from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0012_alter_user_first_name_max_length')]
    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS address', reverse_sql='DROP SCHEMA IF EXISTS address CASCADE'),
        migrations.CreateModel(name='Building', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('fias_guid', models.UUIDField(blank=True, null=True, unique=True)), ('street_fias_guid', models.UUIDField(blank=True, null=True)), ('house_number', models.CharField(max_length=40)), ('full_address', models.TextField()), ('geo_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)), ('geo_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)), ('timezone', models.CharField(blank=True, max_length=64, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_buildings_created', to='auth.user'))], options={'db_table': 'address"."building', 'ordering': ['full_address', 'id']}),
        migrations.CreateModel(name='ImportBatch', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('company_id', models.IntegerField()), ('uploaded_at', models.DateTimeField(auto_now_add=True)), ('planned_date_from', models.DateField()), ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('validated', 'validated'), ('imported', 'imported'), ('failed', 'failed')], default='uploaded', max_length=20)), ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_import_batches', to='auth.user'))], options={'db_table': 'address"."import_batch', 'ordering': ['-uploaded_at', '-id']}),
        migrations.CreateModel(name='Unit', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('unit_number', models.CharField(max_length=30)), ('fias_guid', models.UUIDField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='address.building'))], options={'db_table': 'address"."unit', 'ordering': ['building_id', 'unit_number', 'id']}),
        migrations.CreateModel(name='ImportRow', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('row_no', models.PositiveIntegerField()), ('raw_address', models.TextField(blank=True, default='')), ('city_main', models.CharField(blank=True, default='', max_length=255)), ('district', models.CharField(blank=True, default='', max_length=255)), ('city_fact', models.CharField(blank=True, default='', max_length=255)), ('street', models.CharField(blank=True, default='', max_length=255)), ('house', models.CharField(blank=True, default='', max_length=64)), ('unit_number', models.CharField(blank=True, default='', max_length=30)), ('source_kladr_check', models.CharField(blank=True, default='', max_length=20)), ('house_parse_status', models.CharField(blank=True, default='', max_length=30)), ('house_fias_status', models.CharField(blank=True, default='', max_length=30)), ('binding_status', models.CharField(blank=True, default='', max_length=30)), ('unit_status', models.CharField(blank=True, default='', max_length=30)), ('final_status', models.CharField(blank=True, choices=[('ready', 'ready'), ('blocked', 'blocked'), ('clarify', 'clarify'), ('imported', 'imported'), ('error', 'error')], default='', max_length=20)), ('comment', models.TextField(blank=True, default='')), ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='address.importbatch'))], options={'db_table': 'address"."import_row', 'ordering': ['batch_id', 'row_no', 'id']}),
        migrations.AddConstraint(model_name='building', constraint=models.UniqueConstraint(condition=models.Q(('fias_guid__isnull', True)), fields=('street_fias_guid', 'house_number'), name='uq_address_building_street_house_without_house_guid')),
        migrations.AddIndex(model_name='building', index=models.Index(fields=['street_fias_guid'], name='idx_addr_building_street_guid')),
        migrations.AddIndex(model_name='building', index=models.Index(fields=['house_number'], name='idx_addr_building_house_no')),
        migrations.AddIndex(model_name='building', index=models.Index(fields=['geo_lat', 'geo_lon'], name='idx_addr_building_geo')),
        migrations.AddConstraint(model_name='unit', constraint=models.UniqueConstraint(fields=('building', 'unit_number'), name='uq_address_unit_building_number')),
        migrations.AddConstraint(model_name='unit', constraint=models.UniqueConstraint(condition=models.Q(('fias_guid__isnull', False)), fields=('fias_guid',), name='uq_address_unit_fias_guid')),
        migrations.AddIndex(model_name='unit', index=models.Index(fields=['building', 'unit_number'], name='idx_addr_unit_building_number')),
        migrations.AddConstraint(model_name='importrow', constraint=models.UniqueConstraint(fields=('batch', 'row_no'), name='uq_address_import_row_batch_row_no')),
    ]
