COMMENT ON TABLE public.ai_cost_tracking IS 'Архивная таблица учета стоимости AI-вызовов старой реализации.';
COMMENT ON TABLE public.ai_model_pricing IS 'Архивный справочник цен AI-моделей старой подсистемы.';
COMMENT ON TABLE public.ai_models IS 'Архивный справочник AI-моделей старой подсистемы.';
COMMENT ON TABLE public.ai_providers IS 'Архивный справочник AI-провайдеров старой подсистемы.';
COMMENT ON TABLE public.ai_request_history IS 'Архив истории AI-запросов старой реализации.';
COMMENT ON TABLE public.ai_type_of_service IS 'Архивный справочник типов услуг для старой AI-классификации.';
COMMENT ON TABLE public.auth_group IS 'Системная таблица Django: группы пользователей.';
COMMENT ON TABLE public.auth_group_permissions IS 'Системная таблица Django: права, назначенные группам.';
COMMENT ON TABLE public.auth_permission IS 'Системный справочник Django permissions.';
COMMENT ON TABLE public.auth_user IS 'Основная таблица пользователей Django.';
COMMENT ON TABLE public.auth_user_groups IS 'Системная связка пользователей Django с группами.';
COMMENT ON TABLE public.auth_user_user_permissions IS 'Системная таблица индивидуальных прав пользователей Django.';
COMMENT ON TABLE public.bot_service_requests IS 'Legacy-таблица старой формы заявок; все еще используется старым кабинетом исполнителя в portal.';
COMMENT ON TABLE public.bot_service_requests_backup IS 'Резервная копия legacy-таблицы bot_service_requests.';
COMMENT ON TABLE public.debug_span_log IS 'Пустая отладочная таблица span-логов старой трассировки.';
COMMENT ON TABLE public.debug_trace_log IS 'Пустая отладочная таблица трассировки старой AI-подсистемы.';
COMMENT ON TABLE public.dialog_logs IS 'Основной журнал диалогов пользователей и ответов бота по всем каналам.';
COMMENT ON TABLE public.django_admin_log IS 'Системный журнал действий в Django admin.';
COMMENT ON TABLE public.django_content_type IS 'Системная таблица Django content types.';
COMMENT ON TABLE public.django_migrations IS 'История примененных миграций Django.';
COMMENT ON TABLE public.django_session IS 'Сессии веб-пользователей Django.';
COMMENT ON TABLE public.file_manager_userfile IS 'Файлы, загруженные пользователями через модуль file manager.';
COMMENT ON TABLE public.kladr_building IS 'Справочник зданий адресной подсистемы КЛАДР.';
COMMENT ON TABLE public.kladr_dataimportlog IS 'Журнал импортов данных КЛАДР.';
COMMENT ON TABLE public.kladr_kladraddressobject IS 'Адресные объекты КЛАДР: города, улицы и другие элементы адреса.';
COMMENT ON TABLE public.kladr_kladrobjecttype IS 'Справочник типов адресных объектов КЛАДР.';
COMMENT ON TABLE public.kladr_servicearea IS 'Зоны обслуживания, сформированные на базе адресной подсистемы.';
COMMENT ON TABLE public.kladr_servicearea_buildings IS 'Связка зон обслуживания КЛАДР с конкретными зданиями.';
COMMENT ON TABLE public.llm_request_log IS 'Основной журнал LLM-вызовов: промпты, ответы, стоимость и связка с сессиями.';
COMMENT ON TABLE public.llm_response_cache IS 'Пустой кэш ответов LLM старой реализации.';
COMMENT ON TABLE public.llm_tester_llmtestresult IS 'Результаты тестовых прогонов и экспериментов в подсистеме llm-tester.';
COMMENT ON TABLE public.llm_tester_promptpreset IS 'Пресеты промптов для подсистемы llm-tester.';
COMMENT ON TABLE public.llm_tester_prompttemplate IS 'Шаблоны промптов для подсистемы llm-tester.';
COMMENT ON TABLE public.message_handler_apierrorlog IS 'Журнал ошибок API и интеграций в message handler.';
COMMENT ON TABLE public.message_handler_communicativescript IS 'Коммуникативные скрипты и шаблоны фраз бота.';
COMMENT ON TABLE public.nsi_company IS 'Текущий справочник компаний системы.';
COMMENT ON TABLE public.nsi_equipmenttype IS 'Текущий справочник типов общедомового оборудования.';
COMMENT ON TABLE public.portal_aiprompt IS 'Таблица AI-промптов портала.';
COMMENT ON TABLE public.portal_company IS 'Старый дубль справочника компаний, исторически оставшийся в схеме public.';
COMMENT ON TABLE public.portal_equipmenttype IS 'Старый дубль справочника типов оборудования, исторически оставшийся в схеме public.';
COMMENT ON TABLE public.portal_semanticpattern IS 'Семантические паттерны для распознавания и поиска в портале.';
COMMENT ON TABLE public.portal_userprofile IS 'Профили пользователей портала с бизнес-ролями, основной компанией и подразделением.';
COMMENT ON TABLE public.prompt_template_versions IS 'Старая таблица версий промптов, оставшаяся после ранних экспериментов.';
COMMENT ON TABLE public.prompt_templates IS 'Старая таблица шаблонов промптов, оставшаяся после ранних экспериментов.';
COMMENT ON TABLE public.ref_categories IS 'Текущий справочник категорий услуг ЖКХ.';
COMMENT ON TABLE public.ref_localization IS 'Текущий справочник локализаций услуг: общедомовое или индивидуальное.';
COMMENT ON TABLE public.ref_pricing_units IS 'Справочник единиц тарификации и ценообразования старой структуры.';
COMMENT ON TABLE public.ref_routes IS 'Старый справочник маршрутов в public; новый контур использует request_mgmt.route_ref.';
COMMENT ON TABLE public.ref_service_types IS 'Текущий справочник типов услуги: запрос или инцидент.';
COMMENT ON TABLE public.ref_tags_embeddings IS 'Старая таблица embedding-индекса тегов.';
COMMENT ON TABLE public.service_objects IS 'Объекты обслуживания: дом или помещение, к которым привязываются услуги и заявки.';
COMMENT ON TABLE public.service_tags_backup IS 'Архивная таблица тегов услуг до миграций каталога.';
COMMENT ON TABLE public.services_catalog IS 'Основной каталог услуг ЖКХ, используемый AI-классификацией и маршрутизацией.';
COMMENT ON TABLE public.services_catalog_backup IS 'Резервная копия каталога услуг до переработки структуры.';
COMMENT ON TABLE public.services_catalog_before_fk_restore IS 'Снимок каталога услуг перед восстановлением FK-структуры.';
COMMENT ON TABLE public.services_catalog_old IS 'Историческая версия каталога услуг.';
COMMENT ON TABLE public.tmpoldadres IS 'Временная таблица старых адресов, оставшаяся после миграций.';
COMMENT ON TABLE public.units IS 'Старый справочник помещений и квартир.';
COMMENT ON TABLE public.users IS 'Остаток старой пользовательской таблицы до перехода на Django auth_user.';
COMMENT ON TABLE request_mgmt.company_department IS 'Подразделения компаний для маршрутизации и исполнения заявок.';
COMMENT ON TABLE request_mgmt.company_object_service_period IS 'Периоды обслуживания объектов для компании и услуги.';
COMMENT ON TABLE request_mgmt.company_route_mapping IS 'Правила привязки компаний к маршрутам обработки заявок.';
COMMENT ON TABLE request_mgmt.contractor_organization IS 'Справочник подрядных организаций нового контура заявок.';
COMMENT ON TABLE request_mgmt.notification_outbox IS 'Исходящая очередь уведомлений по заявкам нового контура.';
COMMENT ON TABLE request_mgmt.request_intake IS 'Входящий слой регистрации заявок из внешних каналов и интеграций.';
COMMENT ON TABLE request_mgmt.route_ref IS 'Рабочий справочник маршрутов нового контура заявок.';
COMMENT ON TABLE request_mgmt.sla_instance IS 'Экземпляры SLA по конкретным заявкам.';
COMMENT ON TABLE request_mgmt.sla_policy IS 'Политики SLA по услугам, компаниям и приоритетам.';
COMMENT ON TABLE request_mgmt.user_company_membership IS 'Членство пользователя в компании, подразделении и роли.';
COMMENT ON TABLE request_mgmt.work_order IS 'Главная таблица нового контура заявок ЖКХ.';
COMMENT ON TABLE request_mgmt.work_order_attachment IS 'Вложения и файлы, прикрепленные к заявке нового контура.';
COMMENT ON TABLE request_mgmt.work_order_event_log IS 'Подробный журнал событий и действий по заявке нового контура.';
COMMENT ON TABLE request_mgmt.work_order_status_history IS 'История смены статусов заявок нового контура.';
COMMENT ON TABLE request_mgmt.work_order_status_ref IS 'Справочник статусов заявок нового контура.';
COMMENT ON TABLE request_mgmt.work_order_status_transition IS 'Допустимые переходы между статусами заявок нового контура.';
