# Generated by Django 6.0 on 2026-01-16 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пресета')),
                ('variable_values', models.JSONField(verbose_name='Значения переменных (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Пресет промпта',
                'verbose_name_plural': 'Пресеты промптов',
                'ordering': ['prompt', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название промпта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('prompt_type', models.CharField(choices=[('filter_detection', 'FilterDetectionService'), ('main_agent', 'MainAgent'), ('custom', 'Кастомный')], max_length=50, verbose_name='Тип промпта')),
                ('template', models.TextField(verbose_name='Шаблон промпта (с переменными)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Шаблон промпта',
                'verbose_name_plural': 'Шаблоны промптов',
                'ordering': ['prompt_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yandexgpt', 'YandexGPT'), ('gigachat', 'GigaChat')], max_length=20, verbose_name='Провайдер')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('prompt_text', models.TextField(verbose_name='Отправленный промпт')),
                ('response_text', models.TextField(verbose_name='Ответ LLM')),
                ('usage_info', models.JSONField(verbose_name='Информация об использовании (токены, стоимость)')),
                ('status', models.CharField(choices=[('success', 'Успех'), ('error', 'Ошибка')], default='success', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='llm_tester.promptpreset', verbose_name='Использованный пресет')),
            ],
            options={
                'verbose_name': 'Результат теста LLM',
                'verbose_name_plural': 'Результаты тестов LLM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='promptpreset',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='llm_tester.prompttemplate', verbose_name='Шаблон промпта'),
        ),
    ]
