# Generated by Django 6.0 on 2026-02-05 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_tester', '0002_promptpreset_custom_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptpreset',
            options={'ordering': ['prompt', 'name'], 'verbose_name': 'Тестовый пресет', 'verbose_name_plural': 'Тестовые пресеты'},
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='created_by',
            field=models.ForeignKey(help_text='Кто запустил тест', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Текст ошибки если статус = error', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='model',
            field=models.CharField(help_text='Название модели (например: YandexGPT Pro, GigaChat-2)', max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='preset',
            field=models.ForeignKey(blank=True, help_text='Какой пресет был протестирован', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='llm_tester.promptpreset', verbose_name='Использованный пресет'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='prompt_text',
            field=models.TextField(help_text='Полный текст промпта который был отправлен', verbose_name='Отправленный промпт'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='provider',
            field=models.CharField(choices=[('yandexgpt', 'YandexGPT'), ('gigachat', 'GigaChat')], help_text='LLM провайдер (YandexGPT, GigaChat)', max_length=20, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='response_text',
            field=models.TextField(help_text='Ответ который вернула модель', verbose_name='Ответ LLM'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='status',
            field=models.CharField(choices=[('success', 'Успех'), ('error', 'Ошибка')], default='success', help_text='Успешно ли выполнен запрос', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='llmtestresult',
            name='usage_info',
            field=models.JSONField(help_text='Токены, стоимость, время обработки (JSON)', verbose_name='Метрики'),
        ),
        migrations.AlterField(
            model_name='promptpreset',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Если заполнено - заменяет шаблон', verbose_name='Измененный текст промпта'),
        ),
        migrations.AlterField(
            model_name='promptpreset',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Используется ли этот пресет для тестирования', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='promptpreset',
            name='name',
            field=models.CharField(help_text='Название варианта теста', max_length=200, verbose_name='Название пресета'),
        ),
        migrations.AlterField(
            model_name='promptpreset',
            name='prompt',
            field=models.ForeignKey(help_text='Базовый шаблон для этого пресета', on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='llm_tester.prompttemplate', verbose_name='Шаблон промпта'),
        ),
        migrations.AlterField(
            model_name='promptpreset',
            name='variable_values',
            field=models.JSONField(help_text='JSON с подстановками для переменных шаблона', verbose_name='Значения переменных'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Для чего используется этот шаблон', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Используется ли этот шаблон для тестирования', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(help_text='Название микросервиса или промпта', max_length=200, verbose_name='Название промпта'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='prompt_type',
            field=models.CharField(choices=[('filter_detection', 'FilterDetectionService'), ('main_agent', 'MainAgent'), ('problem_accumulation', 'ProblemAccumulationService'), ('custom', 'Кастомный')], help_text='Какой микросервис использует этот промпт', max_length=50, verbose_name='Тип промпта'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='template',
            field=models.TextField(help_text='Текст промпта с переменными в формате {variable_name}', verbose_name='Шаблон промпта'),
        ),
    ]
