# Generated by Django 6.0 on 2026-03-07 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_tester', '0004_add_microservice_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='parent_version',
            field=models.ForeignKey(
                blank=True,
                help_text='Предыдущая версия этого промпта (для версионирования)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='versions',
                to='llm_tester.prompttemplate',
                verbose_name='Предыдущая версия'
            ),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='version_number',
            field=models.IntegerField(
                default=1,
                help_text='Порядковый номер версии (1, 2, 3, ...)',
                verbose_name='Номер версии'
            ),
        ),
    ]
