# Generated by Django 6.0 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_tester', '0005_add_prompt_versioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='slug',
            field=models.SlugField(
                help_text='Идентификатор промпта (может быть несколько версий с одинаковым slug)',
                max_length=100,
                verbose_name='Slug'
            ),
        ),
    ]
