# Generated by Django 6.0 on 2026-03-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0002_refactor_ref_categories'),
    ]

    operations = [
        # РЕГИСТРАЦИЯ МОДЕЛЕЙ БЕЗ СОЗДАНИЯ ТАБЛИЦ В БД
        #
        # ВОССТАНОВЛЕНО (2026-03-26): FK-структура services_catalog
        #
        # ТАБЛИЦЫ УЖЕ СУЩЕСТВУЮТ В БД:
        #   - ref_categories (создана вручную)
        #   - ref_localization (создана вручную)
        #   - ref_service_types (создана вручную)
        #
        # ИСПОЛЬЗУЕМ SeparateDatabaseAndState:
        #   - state_operations: регистрируем модели в Django (CreateModel)
        #   - database_operations: НИЧЕГО (пустой список) - НЕ создаем таблицы
        #
        # РЕЗУЛЬТАТ:
        #   - Django "увидит" модели
        #   - БД НЕ будет изменена
        #   - Ошибок CREATE TABLE не будет
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='RefCategory',
                    fields=[
                        ('category_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID категории')),
                        ('category_name', models.CharField(max_length=255, verbose_name='Наименование категории')),
                        ('llm_description', models.TextField(help_text='Текстовое описание для использования в AI-системах классификации', verbose_name='Описание для LLM')),
                        ('is_default', models.BooleanField(default=False, help_text='Только одна категория может быть помечена как default', verbose_name='Категория по умолчанию')),
                        ('dev_notes', models.TextField(blank=True, null=True, verbose_name='Заметки разработчика')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                    ],
                    options={
                        'verbose_name': 'Категория услуг',
                        'verbose_name_plural': 'Категории услуг ЖКХ',
                        'db_table': 'ref_categories',
                        'ordering': ['category_id'],
                    },
                ),
                migrations.CreateModel(
                    name='RefLocalization',
                    fields=[
                        ('localization_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID локализации')),
                        ('localization_name', models.CharField(max_length=100, verbose_name='Наименование локализации')),
                        ('llm_description', models.TextField(blank=True, help_text='Текстовое описание для использования в AI-системах классификации', null=True, verbose_name='Описание для LLM')),
                    ],
                    options={
                        'verbose_name': 'Локализация',
                        'verbose_name_plural': 'Локализации',
                        'db_table': 'ref_localization',
                        'ordering': ['localization_id'],
                    },
                ),
                migrations.CreateModel(
                    name='RefServiceType',
                    fields=[
                        ('type_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID типа')),
                        ('type_name', models.CharField(max_length=100, verbose_name='Наименование типа')),
                        ('llm_description', models.TextField(blank=True, help_text='Текстовое описание для использования в AI-системах классификации', null=True, verbose_name='Описание для LLM')),
                    ],
                    options={
                        'verbose_name': 'Тип услуги',
                        'verbose_name_plural': 'Типы услуг',
                        'db_table': 'ref_service_types',
                        'ordering': ['type_id'],
                    },
                ),
            ],
            database_operations=[
                # ПУСТОЙ СПИСОК - НЕ создаем таблицы, они УЖЕ существуют в БД
            ],
        ),
    ]
