# Generated by Django 6.0 on 2026-03-30 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0003_refcategory_reflocalization_refservicetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
        ),
    ]
